language: java
addons:
  sonarcloud:
    organization: inveasy
script:
- mvn clean install sonar:sonar -Dsonar.login=${SONAR_LOGIN} -B -V
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  - provider: releases
    api_key:
      secure: wnUYfdVspRTwEkrRg4upqg7bjfbeOYSbG2Oqm+0jpk/IISTbLN+3fNzbZhqi1MUZlO4fAD05V7ynEpm+NIhvpwSDIJ9FoUo3UU+vOgOdS+DclqRYGmrO4lXCx+97ppfglYmxjUORIqJvXDsnP2v83kgOcyXDNDp1k6bIE0zrEoHzfkIF3n9rR/vPe7htYS453oYJ97EHxw3j/mMjgSebUPbkl7zjFAdv+zkBJH84s310OQvlU6yAwIvTwHuWrfLLWQih2YRFisCqkV6cQUSSk6wge5sUJ8itjmpssqVaZzsd7GBjM2aY9Xqo0x9U9a+eLBDH9/xTpOkBh62+LSLDPpIDstPOPvjJ77xbfNi+xlJluLGKToCP1XReeJITHrUOEiQPHM+FazIFrenxmXPZoF6vVZbiQQdToC2Lf5GRoKTTnx8OBw4XwOsyEzJJTODRK3UXOv++hK355urCHu7jMQq8qc2IeWcTEgw0ZRdmGdje9Z4Xx+Yf0KTPqD0SvFDO9Fl4DtrViMs20wXlR0a1d/0oX3vId9pbsqrJiMLrmb0itXFvv2y3UvC17IhyHu1gECcsfwPMR4eoOfekgM6Heh2abnefeM5bFwHYFyTQ+ee1xx+oVGYwnF5XkRh6Je2GGo3dXiLuGoNwVQ/wSNdeRBpJr7pVS3CuKgvDVWYnHPs=
    file_glob: true
    file: target/*.jar
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$
      tags: true
  - provider: bintray
    file: bintray-descriptor.json
    key:
      secure: i+DzXvoTAuUvaqjPkvDge9nJUdf2xoesVwuE2iLdN1zJdrdWVGYNgrwENMuVauXP9YGFGC29JN+/+MxzRaiCNoBqozZ80mJWGFHjYxUOvY1bdrWXmYOKCJ/0GG3CvHCVVeeV/z8DM7w8N1LPSTOpAq1Nglwyl5xinjOT3bXvp3eEjLOCHG4u0uXTzTDKAX6/X6lyYWu1uVMXcQuK1qSxhXdriEGhOISOoCC3r2qADoFdxL8ZhEFxUlTfzhWQIqBCl/jak8nmjTh14leGo18HZ4JvRbrtz9aLE0ZR3Lcl9yMMnkiOtW25iBHSa2y9Py0HzblsJhyfsUpZyU3So9NEY/pa5nIKiHat5QeiIWL11ebwYcNj6qt/ZTUZdMBOywP4iGOpm7+igP2ShYdHv11IHPst1G0jZPmcEN4LeJNGOiRqb6FmaHqDps8DV45GIJ81JGTgmB4YTgSXS/jmvoOYtiQ3A99+/e63Yv94czhWoG/jzh5ixhfNCUwbfFvKXSedhvf7CDALGj10cWDdO7cklKQmvMqcUuuvpVPgObr5uWSiY63u858bdoAYI3K8+d86eKzre1mAu5TbcTI0Xg5DVH1cwVZ6ZC0twllK1JRuaoDWovzvGkASon0kWS/IjLy12gI8krzuL8+2jKOg8/fBtwEy9vTFgoNzzB9XuEeXwWA=
    user: goveranter
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$
      tags: true